name: run-test
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with: 
          dotnet-versions: "8.0"

      - name: Restore dependence
        run: dotnet Restore

      - name: Build project
        run: dotnet build --no-restore --configuration Release
 
      - name: Run test
        run: dotnet test --no-build --configuration Release --logger "console;verbosity=normal"