name: run-test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
 
    - name: Setup .NET SDK (8.0)
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
 
    - name: Clear NuGet cache
      run: dotnet nuget locals all --clear
 
    - name: Clean previous build
      run: |
        rm -rf ./bin
        rm -rf ./obj
 
    - name: Restore dependencies
      run: dotnet restore
 
    - name: Build project
      run: dotnet build --no-restore --configuration Release
 
    - name: Run tests
      run: dotnet test WordPressApiTests/api_learning.sln --no-build --verbosity normal