name: run-test
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with: 
          dotnet-versions: "9.0"

      - name: Restore dependence
        run: dotnet Restore

      - name: Build project
        run: dotnet Build
      - name: Run test
        run: dotnet test